class RenderDeities{static $getRenderedDeity(deity){return $$`
			${Renderer.utils.getBorderTr()}
			${Renderer.utils.getExcludedTr(deity,"deity")}
			${Renderer.utils.getNameTr(deity,{suffix:deity.title?`, ${deity.title.toTitleCase()}`:"",page:UrlUtil.PG_DEITIES})}
			${RenderDeities._getDeityBody(deity)}
			${deity.reprinted?`<tr class="text"><td colspan="6"><i class="text-muted">Note: this deity has been reprinted in a newer publication.</i></td></tr>`:""}
			${Renderer.utils.getPageTr(deity)}
			${deity.previousVersions?`\n\t\t\t${Renderer.utils.getDividerTr()}\n\t\t\t${deity.previousVersions.map(((d,i)=>RenderDeities._getDeityBody(d,i+1))).join(Renderer.utils.getDividerTr())}\n\t\t\t`:""}
			${Renderer.utils.getBorderTr()}
		`}static _getDeityBody(deity,reprintIndex){const renderer=Renderer.get();const renderStack=[];if(deity.entries){renderer.recursiveRender({entries:[...deity.customExtensionOf?[`{@note This deity is a custom extension of {@deity ${deity.customExtensionOf}} with additional information from <i title="${Parser.sourceJsonToFull(deity.source).escapeQuotes()}">${Parser.sourceJsonToAbv(deity.source)}</i>.}`]:[],...deity.entries]},renderStack)}if(deity.symbolImg)deity.symbolImg.style=deity.symbolImg.style||"deity-symbol";return`\n\t\t\t${reprintIndex?`\n\t\t\t\t<tr><td colspan="6">\n\t\t\t\t<i class="text-muted">\n\t\t\t\t${reprintIndex===1?`This deity is a reprint.`:""} The version below was printed in an older publication (${Parser.sourceJsonToFull(deity.source)}${Renderer.utils.isDisplayPage(deity.page)?`, page ${deity.page}`:""}).\n\t\t\t\t</i>\n\t\t\t\t</td></tr>\n\t\t\t`:""}\n\n\t\t\t${Renderer.deity.getOrderedParts(deity,`<tr><td colspan="6">`,`</td></tr>`)}\n\n\t\t\t${deity.symbolImg?`<tr><td colspan="6">${renderer.render({entries:[deity.symbolImg]})}<div class="mb-2"/></td></tr>`:""}\n\t\t\t${renderStack.length?`<tr class="text"><td class="pt-2" colspan="6">${renderStack.join("")}</td></tr>`:""}\n\t\t\t`}}